#!/bin/bash
directories=0

count_directories() {
for item in "$1"/*; do
if [ -d "$item" ]; then
directories=$((directories + 1))
count_directories "$item"
fi
done
}

count_directories "."

echo "Total directories and sub-directories: $directories"'> count_directories.sh
