#!/bin/bash

count=0

count_directories() {
  for item in "$1"/*; do
    if [ -d "$item" ]; then
      count=$((count + 1))
      count_directories "$item"
    fi
  done
}

count_directories() {
  for item in "$1"/.*; do
    if [[ -d "$item" && ! "$item" =~ /(\.|\.\.)$ ]]; then
      count=$((count + 1))
      count_directories "$item"
    fi
  done
}

count_directories "."

echo "Total directories and sub-directories: $count"
